### ISSUE TITLE
(Suggestion) Remember target and listen channels on restart

### ISSUE THREAD

**Issue by JiFish** [aeolingamenfel/discord-text-adventure-bot#10]
It would be nice if the bot remembered the previously selected target and listen channels.

Either the ability to specify them in the config or writing them somewhere when they are set would solve this.

**Comment by aeolingamenfel** [comment]
Should be fairly straightforward to have some sort of serialized data, I'll add this.

**Comment by JiFish** [comment]
This isn't working for me. I get the following once I try to use either command after `main.json` has been created.

```
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EEXIST: file already exists, open '/home/jifish/adventure-bot/utility/../storage/main.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1222:33)
    at StorageManager.write (/home/jifish/adventure-bot/utility/StorageManager.js:56:12)
    at StorageManager.set (/home/jifish/adventure-bot/utility/StorageManager.js:73:14)
    at MessageHandler.setTargetChannel (/home/jifish/adventure-bot/MessageHandler.js:195:33)
    at MessageHandler.onMessage (/home/jifish/adventure-bot/MessageHandler.js:80:18)
    at DiscordClient.<anonymous> (/home/jifish/adventure-bot/app.js:28:20)
    at emitMany (events.js:127:13)
    at DiscordClient.emit (events.js:201:7)
    at DiscordClient.handleWSMessage (/home/jifish/adventure-bot/node_modules/discord.io/lib/index.js:1734:11)
```

**Comment by aeolingamenfel** [comment]
Hm, alright.

**Comment by aeolingamenfel** [comment]
@JiFish Just pushed a commit to master; see if it works for you.

**Comment by JiFish** [comment]
Fix works perfectly. Thanks for the quick response.

**Comment by aeolingamenfel** [comment]
No problem! Glad to hear it fixed it.
