### ISSUE TITLE
unable to start game

### ISSUE THREAD

**Issue by Astrydax** [aeolingamenfel/discord-text-adventure-bot#25]
Loaded Game: zork
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn dfrotz ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Astrydax** [comment]
on digital ocean droplet

**Comment by aeolingamenfel** [comment]
@Astrydax are you still having this issue?

**Comment by PlushBanshee** [comment]
i'm getting the same error please help i will reply back fast
