### ISSUE TITLE
CRASH ON $start A

### ISSUE THREAD

**Issue by PlushBanshee** [aeolingamenfel/discord-text-adventure-bot#34]
crash on game load and yes i got dfrotz.exe but where do i place it in what path and who to get a .z5 game to run

Loaded Game: A
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn dfrotz ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/59961314-538d4900-9519-11e9-8371-8999fb2c4a7b.png)
config
![image](https://user-images.githubusercontent.com/31914937/59961317-5c7e1a80-9519-11e9-8532-2153d90662a6.png)
games folder
![image](https://user-images.githubusercontent.com/31914937/59961321-69027300-9519-11e9-90be-3f27c8e57d63.png)

**Comment by aeolingamenfel** [comment]
You will need to add dfrotz not to the games folder but to your path. I've assumed that you're using Windows because that screenshot looks like the Windows file explorer, but please correct me if otherwise. In general, you should follow these steps:

1. Move `dfrotz.exe` into `C:\users\{your username}\bin\`
2. Locate the tool to edit your system path. The instructions provided by Oracle for Java ([link](https://www.java.com/en/download/help/path.xml)) are useful, but once you have clicked the "edit" button in Windows, add the following to the end of the path (do **not** wipe out the existing value, just append to it): `C:\users\{your username}\bin\` (or wherever you put `dfrotz.exe`)

Of course, replacing `{your username}` with your actual Windows username. You can verify that you did these steps by performing the following afterwards: opening a new terminal/command line window and typing `dfrotz` and pressing enter. If it gives you some sort of "unrecognized command" or similar, then you have failed. 

Please let me know if those instructions are useful.

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/60063257-a1839600-973f-11e9-9a1d-735c0a4129ad.png)
![image](https://user-images.githubusercontent.com/31914937/60063268-b19b7580-973f-11e9-9964-452fc1bff660.png)

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/60063320-e1e31400-973f-11e9-865a-cc39d540b600.png)
ahh wait linux found it

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/60063429-38e8e900-9740-11e9-96f3-b946fec81ae1.png)
but still crashes and yep im a windows user

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/60064109-b3b30380-9742-11e9-9cf1-c8f1e05aeddb.png)
okay i got this to show in the windows linux terminal i fixed the spelling mistake with the user folder name but it still crashes when i try to run a game

**Comment by PlushBanshee** [comment]
i did sudo npm run start did $targetChannel
$start game and it crashed
![image](https://user-images.githubusercontent.com/31914937/60072894-3f885800-9762-11e9-9e8b-d790604e6530.png)

**Comment by aeolingamenfel** [comment]
Can you try running the game in the terminal using dfrotz directly? IE.

```
dfrotz path\to\{game name}.z5
```

And let me know if that runs as expected?

**Comment by PlushBanshee** [comment]
![image](https://user-images.githubusercontent.com/31914937/60141880-c1c45b00-97fa-11e9-9137-827ccd587416.png)

**Comment by PlushBanshee** [comment]
is there by anychance we can talk this over discord i built bots before but this is new to me adding .exes to node,js scripts i really like the idea of this bot and i got a tone of .z# games ready but i'm still at a loss?

**Comment by aeolingamenfel** [comment]
Per discussion on Discord, this looks like an actual bug with the bot, which I'll try to address. The game in question seems to be `Asylum.z5` from [this link](https://ifarchive.org/indexes/if-archiveXgamesXzcode.html), and repro steps are:

```
$targetChannel
$start Asylum
$south
```

**Comment by aeolingamenfel** [comment]
Cannot reproduce with latest version of bot; please see screenshot below.

**System:** macOS running `dfrotz`.<br /><br />
<img width="764" alt="Screen Shot 2019-07-16 at 3 37 18 PM" src="https://user-images.githubusercontent.com/6314286/61331718-adfb8b80-a7df-11e9-8f54-d9820cc31183.png">

**Comment by KawaiiFiveO** [comment]
Experiencing same issue. dfrotz is installed normally, can be used to play the game from any location.
Bot works until starting a game and entering a command, crashes with the same "throw er, unhandled error event".

Running Raspbian (Debian variant). All packages reinstalled and updated with npm wherever possible.

![Capture](https://user-images.githubusercontent.com/49249543/85042473-1cf40980-b140-11ea-8142-100e4c057ed0.PNG)

[2020-06-18T15_37_36_232Z-debug.log](https://github.com/aeolingamenfel/discord-text-adventure-bot/files/4799599/2020-06-18T15_37_36_232Z-debug.log)

**Comment by aeolingamenfel** [comment]
I've created #39 as a direct copy of your comment, @KawaiiFiveO , just so I can keep the two discussions separate. If it turns out they are related, then I'll update this issue with the findings.

**Comment by aeolingamenfel** [comment]
The bot has been updated to a new framework, so this bug might be solved, but since I couldn't reproduce it, I'll leave it open for a bit.
